version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:8080"

  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh






volumes:
  db_data: