version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "80:8080"

  redis:
    image: "redis:alpine"

    command: redis-server

    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  # db:
  #   image: postgres:12.1
  #   environment:
  #     POSTGRES_PASSWORD: docker
  #     POSTGRES_USER: docker
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./init.sh:/docker-entrypoint-initdb.d/init.sh



# volumes:
#   db_data: