version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:8080"

  database:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - db_data:/var/lib/postgresql/data







volumes:
  db_data: